import type { ToolInputSchema } from "../../contracts/tool.js"
import type { McpLabScenarioV2, LabProfileId } from "../contracts/scenario.js"

export interface LabTool {
  readonly name: string
  readonly title: string
  readonly description: string
  readonly inputSchema: ToolInputSchema
  /** When set, calling this tool requires the scope beyond the environment's required scopes (step-up). */
  readonly requiredScope: string | null
}

const queryOnlySchema: ToolInputSchema = {
  type: "object",
  properties: {
    query: { type: "string", description: "Synthetic test label echoed back in the result.", maxLength: 200 },
  },
  required: [],
  additionalProperties: false,
}

const baseToolNamesByProfile: Readonly<Record<LabProfileId, readonly string[]>> = {
  "standards-conformance": ["conformance_echo", "conformance_catalog_page_a", "conformance_catalog_page_b", "conformance_catalog_page_c"],
  "servicenow-inbound": ["lookup_incidents", "lookup_change_requests", "lookup_kb_articles", "lookup_requested_items"],
  "microsoft-work-iq": ["search_work_content", "search_work_people", "search_work_meetings", "search_work_files"],
  "microsoft-enterprise": ["list_directory_users", "list_directory_groups", "list_directory_applications", "list_directory_devices"],
  "agent-365-mail": ["list_mail_messages", "search_mail_messages", "list_mail_folders", "get_mail_message"],
}

/**
 * Deterministic synthetic tool catalog for one environment. Profiles reproduce
 * documented tool-name shapes only; results are always synthetic and say so.
 * When the scenario declares optional scopes, one additional tool requires the
 * first optional scope so incremental-authorization step-up can be exercised.
 */
export function labToolCatalog(scenario: McpLabScenarioV2): readonly LabTool[] {
  const tools: LabTool[] = baseToolNamesByProfile[scenario.profileId].map((name) => ({
    name,
    title: `Synthetic ${name.replaceAll("_", " ")}`,
    description: `Returns deterministic synthetic ${scenario.profileId} data proving MCP discovery and execution. No provider identity or data is involved.`,
    inputSchema: queryOnlySchema,
    requiredScope: null,
  }))
  const stepUpScope = scenario.authentication.optionalScopes[0]
  if (stepUpScope !== undefined) {
    tools.push({
      name: "export_audit_report",
      title: "Synthetic elevated export",
      description: `Requires the additional '${stepUpScope}' scope so clients can prove insufficient_scope step-up handling.`,
      inputSchema: queryOnlySchema,
      requiredScope: stepUpScope,
    })
  }
  return tools
}

export function syntheticToolResult(
  scenario: McpLabScenarioV2,
  toolName: string,
  argumentsValue: Readonly<Record<string, unknown>>,
  providerRequestId: string,
): Record<string, unknown> {
  return {
    synthetic: true,
    profileId: scenario.profileId,
    tool: toolName,
    requestId: providerRequestId,
    records: [
      {
        id: "lab-record-0001",
        label: "Synthetic lab record",
        detail: "Generated by the OpenWork Diagnostics OAuth/MCP lab; contains no provider data.",
      },
    ],
    arguments: Object.keys(argumentsValue).sort(),
  }
}
